package com.virtualshop.virtualshop.Config;
public class APIs {
    public static final String Userverification     =      "";
    public static final String BUY_STock            =      "http://api2.atscart.com/api/buy_trade";
    public static final String Resell               =      "http://api2.atscart.com/api/reselling" ;
    public static String Manual_FundTransAPi        =      "http://api2.atscart.com/api/manually_jolo_transfer";
    public static String LoginAPI                   =      "http://api2.atscart.com/api/login";
    public static String Mystock                    =      "http://api2.atscart.com/api/show_customer_stock";
    public static String RegisterAPI                =      "http://api2.atscart.com/api/signup";
    public static String ProductlistAPI             =      "http://api2.atscart.com/api/product_by_type";
    public static String lottery_details            =      "http://api2.atscart.com/api/show_lottery";
    public static String balance_detail             =      "http://api2.atscart.com/api/show_balane";
    public static String transaction_detail         =      "http://api2.atscart.com/api/recent_transaction";
    public static String stocktransaction_detail    =      "http://api2.atscart.com/api/stock_recent_transaction";
    public static String offline                    =      "http://api2.atscart.com/api/add_balane_offline";
    public static String lottery_join               =      "http://api2.atscart.com/api/join_lottery";
    public static String viewParticiapnt            =      "http://api2.atscart.com/api/show_participant";
    public static String addmoney                   =      "http://api2.atscart.com/api/add_balane_online";
    public static String update                     =      "http://api2.atscart.com/api/update_api";
    public static String frgpass                    =      "http://api2.atscart.com/forgot_password";
    public static String Showinner                  =      "http://api2.atscart.com/api/show_winner_list";
    public static String shownotification           =      "http://api2.atscart.com/api/final_winner";
    public static String payurl                     =      "http://api2.atscart.com/api/internal_pay";
    public static String recent_lottery             =      "http://api2.atscart.com/api/recent_lottery";
    public static String oldLottery                 =      "http://api2.atscart.com/api/old_lottery";
    public static String referrallist               =      "http://api2.atscart.com/api/customer_referral";
    public static String AgentSignup                =      "http://api2.atscart.com/api/dmr_signup" ;
    public static String Benificiarylist            =      "http://api2.atscart.com/api/activate_beneficiary";
    public static String Addebenificiary            =      "http://api2.atscart.com/api/dmr_beneficiary_reg";
    public static String Addebenificiaryotp         =      "http://api2.atscart.com/api/dmr_beneficiary_reg_validate";
    public static String reSendOtp                  =      "http://api2.atscart.com/api/dmr_beneficiary_reg_validate";
    public static String FundTransAPi               =      "http://api2.atscart.com/api/dmr_transfer";
    public static String Balance                    =      "http://api2.atscart.com/api/balance";
    public static String BeniDelete;
    public static String agentDetail;
    public static String fcm                        =      "http://api2.atscart.com/api/send_single_message";
    public static String devicetoken                =      "http://api2.atscart.com/api/token";
    public static String ACTIVEBenificiarylist      =      "http://api2.atscart.com/api/activate_beneficiary";
    public static String broadcast_fcm              =      "http://api2.atscart.com/api/send_message";
    public static String AddReferral                =      "http://api2.atscart.com/api/add_referral";
    public static String Myshop                     =      "http://api2.atscart.com/api/stock_list_by_id";
    public static String BUY                        =      "http://api2.atscart.com/api/add_stock";
    public static String stock_payment              =      "http://api2.atscart.com/api/stock_payment";
    public static String get_stock                  =      "http://api2.atscart.com/api/show_trade";

    public static String GNSLoginAPI                =      "https://www.gnsbook.com/login";
    public static String social_login               =      "http://api2.atscart.com/api/social_login";
    public static String social_signup               =     "http://api2.atscart.com/api/social_signup";
}